package com.yangdai.opennote.presentation.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF445E91)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFD8E2FF)
private val onPrimaryContainerLight = Color(0xFF001A41)
private val secondaryLight = Color(0xFF575E71)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFDBE2F9)
private val onSecondaryContainerLight = Color(0xFF141B2C)
private val tertiaryLight = Color(0xFF715573)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFFBD7FC)
private val onTertiaryContainerLight = Color(0xFF29132D)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF410002)
private val backgroundLight = Color(0xFFF9F9FF)
private val onBackgroundLight = Color(0xFF1A1B20)
private val surfaceLight = Color(0xFFF9F9FF)
private val onSurfaceLight = Color(0xFF1A1B20)
private val surfaceVariantLight = Color(0xFFE1E2EC)
private val onSurfaceVariantLight = Color(0xFF44474F)
private val outlineLight = Color(0xFF75777F)
private val outlineVariantLight = Color(0xFFC4C6D0)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF2F3036)
private val inverseOnSurfaceLight = Color(0xFFF0F0F7)
private val inversePrimaryLight = Color(0xFFADC6FF)
private val surfaceDimLight = Color(0xFFD9D9E0)
private val surfaceBrightLight = Color(0xFFF9F9FF)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFF3F3FA)
private val surfaceContainerLight = Color(0xFFEDEDF4)
private val surfaceContainerHighLight = Color(0xFFE8E7EE)
private val surfaceContainerHighestLight = Color(0xFFE2E2E9)

private val primaryLightMediumContrast = Color(0xFF274273)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFF5A74A9)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF3B4355)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFF6D7488)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF543A57)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFF886B8A)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFF8C0009)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFDA342E)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFF9F9FF)
private val onBackgroundLightMediumContrast = Color(0xFF1A1B20)
private val surfaceLightMediumContrast = Color(0xFFF9F9FF)
private val onSurfaceLightMediumContrast = Color(0xFF1A1B20)
private val surfaceVariantLightMediumContrast = Color(0xFFE1E2EC)
private val onSurfaceVariantLightMediumContrast = Color(0xFF40434B)
private val outlineLightMediumContrast = Color(0xFF5C5F67)
private val outlineVariantLightMediumContrast = Color(0xFF787A83)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF2F3036)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFF0F0F7)
private val inversePrimaryLightMediumContrast = Color(0xFFADC6FF)
private val surfaceDimLightMediumContrast = Color(0xFFD9D9E0)
private val surfaceBrightLightMediumContrast = Color(0xFFF9F9FF)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFF3F3FA)
private val surfaceContainerLightMediumContrast = Color(0xFFEDEDF4)
private val surfaceContainerHighLightMediumContrast = Color(0xFFE8E7EE)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFE2E2E9)

private val primaryLightHighContrast = Color(0xFF00204E)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF274273)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF1A2233)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF3B4355)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF311A34)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF543A57)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF4E0002)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF8C0009)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFF9F9FF)
private val onBackgroundLightHighContrast = Color(0xFF1A1B20)
private val surfaceLightHighContrast = Color(0xFFF9F9FF)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFE1E2EC)
private val onSurfaceVariantLightHighContrast = Color(0xFF21242B)
private val outlineLightHighContrast = Color(0xFF40434B)
private val outlineVariantLightHighContrast = Color(0xFF40434B)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF2F3036)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFE6ECFF)
private val surfaceDimLightHighContrast = Color(0xFFD9D9E0)
private val surfaceBrightLightHighContrast = Color(0xFFF9F9FF)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFF3F3FA)
private val surfaceContainerLightHighContrast = Color(0xFFEDEDF4)
private val surfaceContainerHighLightHighContrast = Color(0xFFE8E7EE)
private val surfaceContainerHighestLightHighContrast = Color(0xFFE2E2E9)

private val primaryDark = Color(0xFFADC6FF)
private val onPrimaryDark = Color(0xFF102F60)
private val primaryContainerDark = Color(0xFF2B4678)
private val onPrimaryContainerDark = Color(0xFFD8E2FF)
private val secondaryDark = Color(0xFFBFC6DC)
private val onSecondaryDark = Color(0xFF293041)
private val secondaryContainerDark = Color(0xFF3F4759)
private val onSecondaryContainerDark = Color(0xFFDBE2F9)
private val tertiaryDark = Color(0xFFDEBCDF)
private val onTertiaryDark = Color(0xFF402843)
private val tertiaryContainerDark = Color(0xFF583E5B)
private val onTertiaryContainerDark = Color(0xFFFBD7FC)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF111318)
private val onBackgroundDark = Color(0xFFE2E2E9)
private val surfaceDark = Color(0xFF111318)
private val onSurfaceDark = Color(0xFFE2E2E9)
private val surfaceVariantDark = Color(0xFF44474F)
private val onSurfaceVariantDark = Color(0xFFC4C6D0)
private val outlineDark = Color(0xFF8E9099)
private val outlineVariantDark = Color(0xFF44474F)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFE2E2E9)
private val inverseOnSurfaceDark = Color(0xFF2F3036)
private val inversePrimaryDark = Color(0xFF445E91)
private val surfaceDimDark = Color(0xFF111318)
private val surfaceBrightDark = Color(0xFF37393E)
private val surfaceContainerLowestDark = Color(0xFF0C0E13)
private val surfaceContainerLowDark = Color(0xFF1A1B20)
private val surfaceContainerDark = Color(0xFF1E1F25)
private val surfaceContainerHighDark = Color(0xFF282A2F)
private val surfaceContainerHighestDark = Color(0xFF33353A)

private val primaryDarkMediumContrast = Color(0xFFB4CBFF)
private val onPrimaryDarkMediumContrast = Color(0xFF001537)
private val primaryContainerDarkMediumContrast = Color(0xFF7790C7)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
private val secondaryDarkMediumContrast = Color(0xFFC3CAE1)
private val onSecondaryDarkMediumContrast = Color(0xFF0E1626)
private val secondaryContainerDarkMediumContrast = Color(0xFF8991A5)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFFE3C0E3)
private val onTertiaryDarkMediumContrast = Color(0xFF230D28)
private val tertiaryContainerDarkMediumContrast = Color(0xFFA687A8)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
private val errorDarkMediumContrast = Color(0xFFFFBAB1)
private val onErrorDarkMediumContrast = Color(0xFF370001)
private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF111318)
private val onBackgroundDarkMediumContrast = Color(0xFFE2E2E9)
private val surfaceDarkMediumContrast = Color(0xFF111318)
private val onSurfaceDarkMediumContrast = Color(0xFFFBFAFF)
private val surfaceVariantDarkMediumContrast = Color(0xFF44474F)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFC9CAD4)
private val outlineDarkMediumContrast = Color(0xFFA1A2AC)
private val outlineVariantDarkMediumContrast = Color(0xFF81838C)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFE2E2E9)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF282A2F)
private val inversePrimaryDarkMediumContrast = Color(0xFF2C4779)
private val surfaceDimDarkMediumContrast = Color(0xFF111318)
private val surfaceBrightDarkMediumContrast = Color(0xFF37393E)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0C0E13)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF1A1B20)
private val surfaceContainerDarkMediumContrast = Color(0xFF1E1F25)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF282A2F)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF33353A)

private val primaryDarkHighContrast = Color(0xFFFBFAFF)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFB4CBFF)
private val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
private val secondaryDarkHighContrast = Color(0xFFFBFAFF)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFC3CAE1)
private val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
private val tertiaryDarkHighContrast = Color(0xFFFFF9FA)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFE3C0E3)
private val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
private val errorDarkHighContrast = Color(0xFFFFF9F9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
private val onErrorContainerDarkHighContrast = Color(0xFF000000)
private val backgroundDarkHighContrast = Color(0xFF111318)
private val onBackgroundDarkHighContrast = Color(0xFFE2E2E9)
private val surfaceDarkHighContrast = Color(0xFF111318)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF44474F)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFBFAFF)
private val outlineDarkHighContrast = Color(0xFFC9CAD4)
private val outlineVariantDarkHighContrast = Color(0xFFC9CAD4)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFE2E2E9)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF062859)
private val surfaceDimDarkHighContrast = Color(0xFF111318)
private val surfaceBrightDarkHighContrast = Color(0xFF37393E)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF0C0E13)
private val surfaceContainerLowDarkHighContrast = Color(0xFF1A1B20)
private val surfaceContainerDarkHighContrast = Color(0xFF1E1F25)
private val surfaceContainerHighDarkHighContrast = Color(0xFF282A2F)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF33353A)

val LightBlueColors = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inverseSurface = inverseSurfaceLight,
    inversePrimary = inversePrimaryLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
    surfaceBright = surfaceBrightLight,
    surfaceDim = surfaceDimLight,
)


val DarkBlueColors = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inverseSurface = inverseSurfaceDark,
    inversePrimary = inversePrimaryDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
    surfaceBright = surfaceBrightDark,
    surfaceDim = surfaceDimDark,
)