package com.yangdai.opennote.presentation.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF3B6939)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFBCF0B4)
private val onPrimaryContainerLight = Color(0xFF002204)
private val secondaryLight = Color(0xFF3A693A)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFBBF0B5)
private val onSecondaryContainerLight = Color(0xFF002205)
private val tertiaryLight = Color(0xFF006971)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFF9DF0F9)
private val onTertiaryContainerLight = Color(0xFF002023)
private val errorLight = Color(0xFF904A43)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD5)
private val onErrorContainerLight = Color(0xFF3B0907)
private val backgroundLight = Color(0xFFF7FBF1)
private val onBackgroundLight = Color(0xFF191D17)
private val surfaceLight = Color(0xFFF7FBF1)
private val onSurfaceLight = Color(0xFF191D17)
private val surfaceVariantLight = Color(0xFFDEE5D8)
private val onSurfaceVariantLight = Color(0xFF424940)
private val outlineLight = Color(0xFF72796F)
private val outlineVariantLight = Color(0xFFC2C9BD)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF2D322C)
private val inverseOnSurfaceLight = Color(0xFFEFF2E9)
private val inversePrimaryLight = Color(0xFFA1D39A)
private val surfaceDimLight = Color(0xFFD8DBD2)
private val surfaceBrightLight = Color(0xFFF7FBF1)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFF1F5EC)
private val surfaceContainerLight = Color(0xFFECEFE6)
private val surfaceContainerHighLight = Color(0xFFE6E9E0)
private val surfaceContainerHighestLight = Color(0xFFE0E4DB)

private val primaryLightMediumContrast = Color(0xFF1F4C20)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFF517F4E)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF1E4C21)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFF50804F)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF004B51)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFF248089)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFF6E302A)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFAA6057)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFF7FBF1)
private val onBackgroundLightMediumContrast = Color(0xFF191D17)
private val surfaceLightMediumContrast = Color(0xFFF7FBF1)
private val onSurfaceLightMediumContrast = Color(0xFF191D17)
private val surfaceVariantLightMediumContrast = Color(0xFFDEE5D8)
private val onSurfaceVariantLightMediumContrast = Color(0xFF3E453C)
private val outlineLightMediumContrast = Color(0xFF5A6157)
private val outlineVariantLightMediumContrast = Color(0xFF767D72)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF2D322C)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFEFF2E9)
private val inversePrimaryLightMediumContrast = Color(0xFFA1D39A)
private val surfaceDimLightMediumContrast = Color(0xFFD8DBD2)
private val surfaceBrightLightMediumContrast = Color(0xFFF7FBF1)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFF1F5EC)
private val surfaceContainerLightMediumContrast = Color(0xFFECEFE6)
private val surfaceContainerHighLightMediumContrast = Color(0xFFE6E9E0)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFE0E4DB)

private val primaryLightHighContrast = Color(0xFF002905)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF1F4C20)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF002907)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF1E4C21)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF00272A)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF004B51)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF44100C)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF6E302A)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFF7FBF1)
private val onBackgroundLightHighContrast = Color(0xFF191D17)
private val surfaceLightHighContrast = Color(0xFFF7FBF1)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFDEE5D8)
private val onSurfaceVariantLightHighContrast = Color(0xFF1F261E)
private val outlineLightHighContrast = Color(0xFF3E453C)
private val outlineVariantLightHighContrast = Color(0xFF3E453C)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF2D322C)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFC5FABD)
private val surfaceDimLightHighContrast = Color(0xFFD8DBD2)
private val surfaceBrightLightHighContrast = Color(0xFFF7FBF1)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFF1F5EC)
private val surfaceContainerLightHighContrast = Color(0xFFECEFE6)
private val surfaceContainerHighLightHighContrast = Color(0xFFE6E9E0)
private val surfaceContainerHighestLightHighContrast = Color(0xFFE0E4DB)

private val primaryDark = Color(0xFFA1D39A)
private val onPrimaryDark = Color(0xFF0A390F)
private val primaryContainerDark = Color(0xFF235024)
private val onPrimaryContainerDark = Color(0xFFBCF0B4)
private val secondaryDark = Color(0xFFA0D49B)
private val onSecondaryDark = Color(0xFF083910)
private val secondaryContainerDark = Color(0xFF225025)
private val onSecondaryContainerDark = Color(0xFFBBF0B5)
private val tertiaryDark = Color(0xFF81D3DD)
private val onTertiaryDark = Color(0xFF00363B)
private val tertiaryContainerDark = Color(0xFF004F55)
private val onTertiaryContainerDark = Color(0xFF9DF0F9)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF561E19)
private val errorContainerDark = Color(0xFF73342D)
private val onErrorContainerDark = Color(0xFFFFDAD5)
private val backgroundDark = Color(0xFF10140F)
private val onBackgroundDark = Color(0xFFE0E4DB)
private val surfaceDark = Color(0xFF10140F)
private val onSurfaceDark = Color(0xFFE0E4DB)
private val surfaceVariantDark = Color(0xFF424940)
private val onSurfaceVariantDark = Color(0xFFC2C9BD)
private val outlineDark = Color(0xFF8C9388)
private val outlineVariantDark = Color(0xFF424940)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFE0E4DB)
private val inverseOnSurfaceDark = Color(0xFF2D322C)
private val inversePrimaryDark = Color(0xFF3B6939)
private val surfaceDimDark = Color(0xFF10140F)
private val surfaceBrightDark = Color(0xFF363A34)
private val surfaceContainerLowestDark = Color(0xFF0B0F0A)
private val surfaceContainerLowDark = Color(0xFF191D17)
private val surfaceContainerDark = Color(0xFF1D211B)
private val surfaceContainerHighDark = Color(0xFF272B25)
private val surfaceContainerHighestDark = Color(0xFF323630)

private val primaryDarkMediumContrast = Color(0xFFA5D89E)
private val onPrimaryDarkMediumContrast = Color(0xFF001C03)
private val primaryContainerDarkMediumContrast = Color(0xFF6D9C68)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
private val secondaryDarkMediumContrast = Color(0xFFA4D89F)
private val onSecondaryDarkMediumContrast = Color(0xFF001B03)
private val secondaryContainerDarkMediumContrast = Color(0xFF6C9D69)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFF85D8E1)
private val onTertiaryDarkMediumContrast = Color(0xFF001A1C)
private val tertiaryContainerDarkMediumContrast = Color(0xFF489DA6)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
private val errorDarkMediumContrast = Color(0xFFFFBAB1)
private val onErrorDarkMediumContrast = Color(0xFF330403)
private val errorContainerDarkMediumContrast = Color(0xFFCC7B72)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF10140F)
private val onBackgroundDarkMediumContrast = Color(0xFFE0E4DB)
private val surfaceDarkMediumContrast = Color(0xFF10140F)
private val onSurfaceDarkMediumContrast = Color(0xFFF9FCF3)
private val surfaceVariantDarkMediumContrast = Color(0xFF424940)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFC6CDC1)
private val outlineDarkMediumContrast = Color(0xFF9EA59A)
private val outlineVariantDarkMediumContrast = Color(0xFF7E857B)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFE0E4DB)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF272B25)
private val inversePrimaryDarkMediumContrast = Color(0xFF255125)
private val surfaceDimDarkMediumContrast = Color(0xFF10140F)
private val surfaceBrightDarkMediumContrast = Color(0xFF363A34)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0B0F0A)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF191D17)
private val surfaceContainerDarkMediumContrast = Color(0xFF1D211B)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF272B25)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF323630)

private val primaryDarkHighContrast = Color(0xFFF1FFEA)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFA5D89E)
private val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
private val secondaryDarkHighContrast = Color(0xFFF1FFEA)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFA4D89F)
private val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
private val tertiaryDarkHighContrast = Color(0xFFEFFDFF)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFF85D8E1)
private val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
private val errorDarkHighContrast = Color(0xFFFFF9F9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
private val onErrorContainerDarkHighContrast = Color(0xFF000000)
private val backgroundDarkHighContrast = Color(0xFF10140F)
private val onBackgroundDarkHighContrast = Color(0xFFE0E4DB)
private val surfaceDarkHighContrast = Color(0xFF10140F)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF424940)
private val onSurfaceVariantDarkHighContrast = Color(0xFFF7FDF0)
private val outlineDarkHighContrast = Color(0xFFC6CDC1)
private val outlineVariantDarkHighContrast = Color(0xFFC6CDC1)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFE0E4DB)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF023209)
private val surfaceDimDarkHighContrast = Color(0xFF10140F)
private val surfaceBrightDarkHighContrast = Color(0xFF363A34)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF0B0F0A)
private val surfaceContainerLowDarkHighContrast = Color(0xFF191D17)
private val surfaceContainerDarkHighContrast = Color(0xFF1D211B)
private val surfaceContainerHighDarkHighContrast = Color(0xFF272B25)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF323630)

val LightGreenColors = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inverseSurface = inverseSurfaceLight,
    inversePrimary = inversePrimaryLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
    surfaceBright = surfaceBrightLight,
    surfaceDim = surfaceDimLight,
)


val DarkGreenColors = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inverseSurface = inverseSurfaceDark,
    inversePrimary = inversePrimaryDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
    surfaceBright = surfaceBrightDark,
    surfaceDim = surfaceDimDark,
)