package com.yangdai.opennote.presentation.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF7F4D7A)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFFFD7F6)
private val onPrimaryContainerLight = Color(0xFF330833)
private val secondaryLight = Color(0xFF7F4D7B)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFFFD7F7)
private val onSecondaryContainerLight = Color(0xFF330833)
private val tertiaryLight = Color(0xFF8F4C37)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFFFDBD1)
private val onTertiaryContainerLight = Color(0xFF3A0B00)
private val errorLight = Color(0xFF904A43)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD5)
private val onErrorContainerLight = Color(0xFF3B0907)
private val backgroundLight = Color(0xFFFFF7F9)
private val onBackgroundLight = Color(0xFF201A1E)
private val surfaceLight = Color(0xFFFFF7F9)
private val onSurfaceLight = Color(0xFF201A1E)
private val surfaceVariantLight = Color(0xFFEEDEE7)
private val onSurfaceVariantLight = Color(0xFF4E444B)
private val outlineLight = Color(0xFF80747C)
private val outlineVariantLight = Color(0xFFD1C2CB)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF352E33)
private val inverseOnSurfaceLight = Color(0xFFFAEDF4)
private val inversePrimaryLight = Color(0xFFF1B3E7)
private val surfaceDimLight = Color(0xFFE3D7DD)
private val surfaceBrightLight = Color(0xFFFFF7F9)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFFDF0F7)
private val surfaceContainerLight = Color(0xFFF7EBF1)
private val surfaceContainerHighLight = Color(0xFFF1E5EB)
private val surfaceContainerHighestLight = Color(0xFFEBDFE6)

private val primaryLightMediumContrast = Color(0xFF61325D)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFF986391)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF60325D)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFF976392)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF6D311F)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFFAA614B)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFF6E302A)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFAA6057)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFFFF7F9)
private val onBackgroundLightMediumContrast = Color(0xFF201A1E)
private val surfaceLightMediumContrast = Color(0xFFFFF7F9)
private val onSurfaceLightMediumContrast = Color(0xFF201A1E)
private val surfaceVariantLightMediumContrast = Color(0xFFEEDEE7)
private val onSurfaceVariantLightMediumContrast = Color(0xFF4A4047)
private val outlineLightMediumContrast = Color(0xFF675C63)
private val outlineVariantLightMediumContrast = Color(0xFF83777F)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF352E33)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFFAEDF4)
private val inversePrimaryLightMediumContrast = Color(0xFFF1B3E7)
private val surfaceDimLightMediumContrast = Color(0xFFE3D7DD)
private val surfaceBrightLightMediumContrast = Color(0xFFFFF7F9)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFFDF0F7)
private val surfaceContainerLightMediumContrast = Color(0xFFF7EBF1)
private val surfaceContainerHighLightMediumContrast = Color(0xFFF1E5EB)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFEBDFE6)

private val primaryLightHighContrast = Color(0xFF3B103A)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF61325D)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF3B103A)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF60325D)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF431103)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF6D311F)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF44100C)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF6E302A)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFFFF7F9)
private val onBackgroundLightHighContrast = Color(0xFF201A1E)
private val surfaceLightHighContrast = Color(0xFFFFF7F9)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFEEDEE7)
private val onSurfaceVariantLightHighContrast = Color(0xFF2A2128)
private val outlineLightHighContrast = Color(0xFF4A4047)
private val outlineVariantLightHighContrast = Color(0xFF4A4047)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF352E33)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFFFE5F7)
private val surfaceDimLightHighContrast = Color(0xFFE3D7DD)
private val surfaceBrightLightHighContrast = Color(0xFFFFF7F9)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFFDF0F7)
private val surfaceContainerLightHighContrast = Color(0xFFF7EBF1)
private val surfaceContainerHighLightHighContrast = Color(0xFFF1E5EB)
private val surfaceContainerHighestLightHighContrast = Color(0xFFEBDFE6)

private val primaryDark = Color(0xFFF1B3E7)
private val onPrimaryDark = Color(0xFF4C1F49)
private val primaryContainerDark = Color(0xFF653661)
private val onPrimaryContainerDark = Color(0xFFFFD7F6)
private val secondaryDark = Color(0xFFF0B3E7)
private val onSecondaryDark = Color(0xFF4B1F4A)
private val secondaryContainerDark = Color(0xFF653662)
private val onSecondaryContainerDark = Color(0xFFFFD7F7)
private val tertiaryDark = Color(0xFFFFB59F)
private val onTertiaryDark = Color(0xFF561F0E)
private val tertiaryContainerDark = Color(0xFF723522)
private val onTertiaryContainerDark = Color(0xFFFFDBD1)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF561E19)
private val errorContainerDark = Color(0xFF73342D)
private val onErrorContainerDark = Color(0xFFFFDAD5)
private val backgroundDark = Color(0xFF171216)
private val onBackgroundDark = Color(0xFFEBDFE6)
private val surfaceDark = Color(0xFF171216)
private val onSurfaceDark = Color(0xFFEBDFE6)
private val surfaceVariantDark = Color(0xFF4E444B)
private val onSurfaceVariantDark = Color(0xFFD1C2CB)
private val outlineDark = Color(0xFF9A8D95)
private val outlineVariantDark = Color(0xFF4E444B)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFEBDFE6)
private val inverseOnSurfaceDark = Color(0xFF352E33)
private val inversePrimaryDark = Color(0xFF7F4D7A)
private val surfaceDimDark = Color(0xFF171216)
private val surfaceBrightDark = Color(0xFF3E373C)
private val surfaceContainerLowestDark = Color(0xFF120D11)
private val surfaceContainerLowDark = Color(0xFF201A1E)
private val surfaceContainerDark = Color(0xFF241E22)
private val surfaceContainerHighDark = Color(0xFF2F282D)
private val surfaceContainerHighestDark = Color(0xFF3A3338)

private val primaryDarkMediumContrast = Color(0xFFF5B7EB)
private val onPrimaryDarkMediumContrast = Color(0xFF2D032D)
private val primaryContainerDarkMediumContrast = Color(0xFFB77EAF)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
private val secondaryDarkMediumContrast = Color(0xFFF5B7EC)
private val onSecondaryDarkMediumContrast = Color(0xFF2D032E)
private val secondaryContainerDarkMediumContrast = Color(0xFFB67FAF)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFFFFBBA7)
private val onTertiaryDarkMediumContrast = Color(0xFF310700)
private val tertiaryContainerDarkMediumContrast = Color(0xFFCB7C65)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
private val errorDarkMediumContrast = Color(0xFFFFBAB1)
private val onErrorDarkMediumContrast = Color(0xFF330403)
private val errorContainerDarkMediumContrast = Color(0xFFCC7B72)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF171216)
private val onBackgroundDarkMediumContrast = Color(0xFFEBDFE6)
private val surfaceDarkMediumContrast = Color(0xFF171216)
private val onSurfaceDarkMediumContrast = Color(0xFFFFF9FA)
private val surfaceVariantDarkMediumContrast = Color(0xFF4E444B)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFD5C7CF)
private val outlineDarkMediumContrast = Color(0xFFAD9FA8)
private val outlineVariantDarkMediumContrast = Color(0xFF8C8088)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFEBDFE6)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF2F282D)
private val inversePrimaryDarkMediumContrast = Color(0xFF663762)
private val surfaceDimDarkMediumContrast = Color(0xFF171216)
private val surfaceBrightDarkMediumContrast = Color(0xFF3E373C)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF120D11)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF201A1E)
private val surfaceContainerDarkMediumContrast = Color(0xFF241E22)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF2F282D)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF3A3338)

private val primaryDarkHighContrast = Color(0xFFFFF9FA)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFF5B7EB)
private val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
private val secondaryDarkHighContrast = Color(0xFFFFF9FA)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFF5B7EC)
private val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
private val tertiaryDarkHighContrast = Color(0xFFFFF9F8)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFFFBBA7)
private val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
private val errorDarkHighContrast = Color(0xFFFFF9F9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
private val onErrorContainerDarkHighContrast = Color(0xFF000000)
private val backgroundDarkHighContrast = Color(0xFF171216)
private val onBackgroundDarkHighContrast = Color(0xFFEBDFE6)
private val surfaceDarkHighContrast = Color(0xFF171216)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF4E444B)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFFF9FA)
private val outlineDarkHighContrast = Color(0xFFD5C7CF)
private val outlineVariantDarkHighContrast = Color(0xFFD5C7CF)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFEBDFE6)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF441842)
private val surfaceDimDarkHighContrast = Color(0xFF171216)
private val surfaceBrightDarkHighContrast = Color(0xFF3E373C)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF120D11)
private val surfaceContainerLowDarkHighContrast = Color(0xFF201A1E)
private val surfaceContainerDarkHighContrast = Color(0xFF241E22)
private val surfaceContainerHighDarkHighContrast = Color(0xFF2F282D)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF3A3338)

val LightPurpleColors = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inverseSurface = inverseSurfaceLight,
    inversePrimary = inversePrimaryLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
    surfaceBright = surfaceBrightLight,
    surfaceDim = surfaceDimLight,
)


val DarkPurpleColors = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inverseSurface = inverseSurfaceDark,
    inversePrimary = inversePrimaryDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
    surfaceBright = surfaceBrightDark,
    surfaceDim = surfaceDimDark,
)